esphome:
  name: voice-assistant
  friendly_name: voice-assistant

  on_boot:
    - light.turn_on:
        id: status_leds
        brightness: 80%
        red: 10%
        green: 78%
        blue: 100%
        transition_length: 500ms

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 40MHz

logger: {}

api:
  encryption:
    key: !secret api_encryption_key
  
  on_client_connected:
    - light.turn_off:
        id: status_leds
        transition_length: 500ms

    - delay: 50ms
    
    - micro_wake_word.start: {}

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Voice-Assistant Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal: {}

i2s_audio:
  - id: i2s # For microphone
    i2s_lrclk_pin: GPIO6  #WS 
    i2s_bclk_pin: GPIO7 #SCK

microphone:
  - platform: i2s_audio
    id: va_mic
    adc_type: external
    i2s_din_pin: GPIO4 #SD
    channel: left
    i2s_audio_id: i2s
    pdm: false
    bits_per_sample: 32bit

speaker:
  platform: i2s_audio
  id: va_speaker
  i2s_audio_id: i2s
  dac_type: external
  i2s_dout_pin:   
    number: GPIO8 #DIN Pin of the MAX98357A Audio Amplifier
    allow_other_uses: true
  channel: mono
  bits_per_sample: 16bit
  sample_rate: 8000
  buffer_duration: 1000ms

output:
  - platform: gpio
    pin: 
      number: GPIO8
      allow_other_uses: true
    id: set_low_speaker

micro_wake_word:
  models:
    - model: okay_nabu
      internal: true

  on_wake_word_detected:
    - voice_assistant.start: {}

number:
  - platform: template
    name: "Volume"
    id: volume
    unit_of_measurement: "%"
    min_value: 1
    max_value: 100
    step: 1
    mode: SLIDER
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 80
    icon: "mdi:knob"
    entity_category: config
    on_value:
      - speaker.volume_set: !lambda "return (float) x / 100;"

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    rgb_order: GRB
    pin: GPIO10
    num_leds: 4
    id: status_leds
    name: "Status LEDs"
    effects:
      - pulse:
          name: "Answering"
          transition_length: 300ms
          min_brightness: 20%
          max_brightness: 60%
          update_interval: 800ms

      - addressable_lambda:
          name: 'Thinking'
          update_interval: 20ms
          lambda: |-
            static float wave_pos = 0.0;
            static int direction = 1;
            const float speed = 0.1;
            const float radius = 2.0;
            const int max_brightness = 255;
            const int num_leds = it.size();

            for (int i = 0; i < num_leds; i++) {
              float distance = fabs(wave_pos - i);

              float val = 0.0;
              if (distance <= radius) {
                val = pow(1.0 - (distance / radius), 2);
              }

              int brightness = (int)(val * max_brightness);
              it[i] = Color(brightness, brightness, brightness);
            }

            wave_pos += direction * speed;

            if (wave_pos >= num_leds - 1) {
              wave_pos = num_leds - 1;
              direction = -1;
            } else if (wave_pos <= 0) {
              wave_pos = 0;
              direction = 1;
            }

voice_assistant:
  id: va
  microphone: va_mic
  speaker: va_speaker
  noise_suppression_level: 1.0

  on_start: {}
  
  on_end:
    - wait_until:
        not:
          voice_assistant.is_running: {}

    - micro_wake_word.start: {}

  on_listening:
    - light.turn_on:
        id: status_leds
        brightness: 50%
        red: 100%
        green: 100%
        blue: 100%
        transition_length: 500ms

  on_stt_end: 
    - light.turn_on:
        id: status_leds
        brightness: 80%
        effect: 'Thinking'

  on_tts_stream_start:
    - light.turn_on:
        id: status_leds
        brightness: 30%
        transition_length: 500ms

    - delay: 500ms

    - light.turn_on:
        id: status_leds
        brightness: 60%
        effect: 'Answering'
  
  on_tts_stream_end: 
    - light.turn_off:
        id: status_leds
        transition_length: 500ms
