esphome:
  name: 'voice_assistant'
  friendly_name: 'Voice Assistant'
  comment: 'A local voice assistant'

  environment_variables: {}
  
  on_boot: {}

  on_shutdown: {}

  on_loop: {}

wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password
