name: Berechne Tensor Arena Size (C++)

on:
  push:
    paths:
      - "**/*.tflite"
  workflow_dispatch:

jobs:
  arena-cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make build-essential

      - name: Clone tflite-find-arena-size Submodule
        run: |
          git clone --depth=1 https://github.com/Kanaderu/tflite-find-arena-size.git tools/tflite-find-arena-size

      - name: Build C++ Tool
        run: |
          cd tools/tflite-find-arena-size
          make -f Makefile.tflite
          ls -l build/find-arena-size

      - name: Find and Run `.tflite` Models
        run: |
          echo "Gefundene .tflite Modelle:"
          find . -type f -name "*.tflite"
          for model in $(find . -type f -name "*.tflite"); do
            echo "Modell: $model"
            tools/tflite-find-arena-size/build/find-arena-size "$model"
          done
